# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc7a505b933bac995e232636203c427331ba5db45c4f7e34a4a2c708001688ae5fcdd7163ced0bcfc1c94b82533ad323399afcc817df392aee8094045dda00a3

test:
  secret_key_base: b3841449545c82c63380ac59621c674ee166c68af9e3b798dfb46a43d297aeabbea7ae6a86e1f70fe5e1cd1a47d2d6a60db52228259a63ea8c74f29a64c290b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
